/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2026-02-06 15:42:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import model.*;
import controller.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("controller");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("model");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title> MaListe </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>Modifier</h1>\n");
      out.write("\n");
      out.write("<h3>Petit menu</h3>\n");
      out.write("<a href='Control?action=voir&n=-1'>Voir une partie</a> <br>\n");
      out.write("<a href='Control?action=modifier&pno=-1&jno1=-1&jno2=-1&date=toto&statut=tata'>Modifier une partie</a> <br>\n");
      out.write("<a href='Control?action=list'>Lister les parties</a> <br>\n");
      out.write("<a href='Control?action=delete&pno=-1'>Supprimer une partie</a> <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("</br>\n");
      out.write("<form action='Control'>\n");
      out.write("<input type='hidden' name='action' value='modifier'>\n");
      out.write("<p>Rentrez l'id de partie voulu</p>\n");
      out.write("<input type='text' name='pno'><br>\n");
      out.write("<p>Sélectionnez les joueurs</p>\n");

List<Joueur> joueurs = (ArrayList<Joueur>) request.getAttribute("joueurs");
out.println("<select name='jno1'>");
for(Joueur joueur : joueurs) {
    int jno = joueur.getJno();
    String pseudo = joueur.getPseudo() ;
    out.println("<option value='"+jno+"'>"+pseudo+"</option>");
}
out.println("</select>");

out.println("<select name='jno2'>");
for(Joueur joueur : joueurs) {
    int jno = joueur.getJno();
    String pseudo = joueur.getPseudo() ;
    out.println("<option value='"+jno+"'>"+pseudo+"</option>");
}
out.println("</select>");

      out.write("\n");
      out.write("<p>Rentrez la nouvelle date voulue</p>\n");
      out.write("<input type='date' name='date'>\n");
      out.write("<p>Sélectionnez le statut</p>\n");
      out.write("<select name=\"statut\">\n");
      out.write("  <option value=\"\">--Veuillez choisir une option--</option>\n");
      out.write("  <option value=\"Non commencée\">Non commencée</option>\n");
      out.write("  <option value=\"En cours\">En cours</option>\n");
      out.write("  <option value=\"Terminée\">Terminée</option>\n");
      out.write("</select>\n");
      out.write("\n");
      out.write("<input type='submit'>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
