# test API bruno en utilisant le docker-compose

stages:
  - Test Bruno

test:
  stage: Test Bruno
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose up -d --build
    - until docker compose exec -T ecodrop-db pg_isready -U baptistelavogiezetu; do sleep 1; done
    - until docker compose exec -T ecodrop curl -sf localhost:8080/ecodrop/points > /dev/null; do sleep 1; done
    - docker compose logs ecodrop
    - docker compose exec -T ecodrop bash -c "curl localhost:8080/ecodrop/points"
    - docker compose exec -T ecodrop bash -c "cd /bruno && bru run --env local --tests-only"
  after_script:
    - docker compose down

