name: Push image GHCR

on:
  push:
    branches: [ "main", "master" ]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          IMAGE=ghcr.io/blavogiez/ecodrop:latest
          docker build -t $IMAGE .
          docker push $IMAGE
