name: Test Bruno sur les conteneurs

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: installer docker !
        run: 
          apt-get update -y &&
          apt-get full-upgrade &&
          apt-get install -y docker

      - name: Run le script de démo
        run: chmod +x run*.sh && run-docker.sh 
